// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using Foundation;
using UIKit;

namespace OneTradeCentral.iOS
{
	public partial class StoreListCell : UITableViewCell
	{
		
		public static readonly NSString CellID = new NSString ("CustomerCell");

		public StoreListCell (IntPtr handle) :  base (UITableViewCellStyle.Value1, CellID)
		{
		}
	}
}
