// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace OneTradeCentral.iOS
{
	public partial class ClientSearchTableViewController : UITableViewController
	{
		public ClientSearchTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
