// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace OneTradeCentral.iOS
{
	public partial class CustomerListController : UITableViewController
	{
		public CustomerListController (IntPtr handle) : base (handle)
		{
		}
	}
}
