// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace OneTradeCentral.iOS
{
	public partial class CustomerEditorController : UIViewController
	{
		public CustomerEditorController (IntPtr handle) : base (handle)
		{
		}
	}
}
