// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace OneTradeCentral.iOS
{
	public partial class DatePickerController : UIViewController
	{

		public NSDate SelectedDate { get; set; }

		public OrderViewController _orderViewController { get; set; }

		public DatePickerController (IntPtr handle) : base (handle)
		{

		}

		public DatePickerController(OrderViewController _orderView)
		{
			this._orderViewController = _orderView;
		}
			
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			datePicker.Mode = UIDatePickerMode.Date;
			datePicker.MinimumDate = NSDate.Now;

			if (this._orderViewController.RequestedReleaseDate != null)
				datePicker.Date = this._orderViewController.RequestedReleaseDate;
			else
				datePicker.Date = NSDate.Now;

			datePicker.ValueChanged += (object sender, EventArgs e) => {
				NSDateFormatter dateFormatter = new NSDateFormatter () {
					DateFormat = "dd MMMM yyyy"
				};
						
				this._orderViewController.RequestedReleaseDate = datePicker.Date;

				if (dateFormatter.ToString (NSDate.Now) != dateFormatter.ToString (datePicker.Date)){
					this._orderViewController.ReleaseDateField.Text = dateFormatter.ToString (datePicker.Date);
				}
				else{
					this._orderViewController.ReleaseDateField.Text = "Today";
				}
			};
				
		}

	}

}
