// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using Foundation;
using UIKit;

using OneTradeCentral.DTOs;

namespace OneTradeCentral.iOS
{
	public partial class OrderStatusController : UIViewController
	{


		public OrderStatusController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			ShowStats ();
		}

		void ShowStats ()
		{
			DALFacade dal = new DALFacade ();
			int salesRepAccountID = (int) dal.getUserAccount ().AccountID;
			TotalCountLabel.Text = dal.CountOrders (salesRepAccountID).ToString ();
			PendingCountLabel.Text = dal.CountPendingOrders (salesRepAccountID).ToString ();
			PartialCountLabel.Text = dal.CountPartialOrders (salesRepAccountID).ToString ();
			CompletedCountLabel.Text = dal.CountCompletedOrders (salesRepAccountID).ToString ();
			dal = null;
		}

		partial void RefreshStats (Foundation.NSObject sender) {
//			Logger.log("Refreshing Order Stats...");
			ShowStats();
		}


//		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
//		{
//			base.PrepareForSegue (segue, sender);
//			if (segue.Identifier == "TestIdentifier") {
//				var logViewerController = segue.DestinationViewController as LogViewController;
//				logViewerController.orderStatusController = this;
//
//			}
//		}
//			
	}
}
