// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace OneTradeCentral.iOS
{
	public partial class ProductListingsController : UIViewController
	{
		public ProductListingsController (IntPtr handle) : base (handle)
		{
		}
	}
}
