// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace OneTradeCentral.iOS
{
	[Register ("StoresListingController")]
	public partial class StoresListingController : UITableViewController
	{
		public StoresListingController (IntPtr handle) : base (handle)
		{
		}
	}
}
