// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace OneTradeCentral.iOS
{
	public partial class HoldDateController : UIViewController
	{
		public OrderViewController OrderController { get; set; }

		public HoldDateController (IntPtr handle) : base (handle)
		{
		}
	}
}
