// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;
using CoreGraphics;

using Foundation;
using AssetsLibrary;
using UIKit;

namespace OneTradeCentral.iOS
{
	public partial class OrderLineScannerController : UIViewController
	{
		static UIImagePickerController _imagePicker;
		public UIPopoverController popController { get; set; }
		public OrderViewController OrderViewController { get; set; }

		UIImage ProductImage { get; set; }

		public OrderLineScannerController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
		}

		partial void dismiss (NSObject sender)
		{
			DismissViewController (true, null);
		}

		public override void DismissViewController (bool animated, Action completionHandler)
		{
			popController.Dismiss(animated);
			base.DismissViewController (animated, completionHandler);
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);
			if (segue.Identifier == "ScannerSegue") {
				_imagePicker = segue.DestinationViewController as UIImagePickerController;
				var scannerDelegate = new ScannerCameraDelegate (this);
				scannerDelegate.setCallback ((obj) => {
					var photo = obj.ValueForKey (new NSString ("UIImagePickerControllerOriginalImage")) as UIImage;
					ProductImage = photo;
					var meta = obj.ValueForKey (new NSString ("UIImagePickerControllerMediaMetadata")) as NSDictionary;
					ALAssetsLibrary library = new ALAssetsLibrary ();                   
					library.WriteImageToSavedPhotosAlbum (photo.CGImage, meta, (assetUrl, error) => {
						Logger.log ("assetUrl:" + assetUrl);
					});
				});
				_imagePicker.Delegate = scannerDelegate;
			} else if (segue.Identifier == "ProductScannedSegue") {
				var scannedProductController = segue.DestinationViewController as ScannedProductController;
				scannedProductController.OrderViewController = OrderViewController;
				scannedProductController.setProductImage (ProductImage);
			}

		} 
		
		class ScannerCameraDelegate : UIImagePickerControllerDelegate
		{
			static Action<NSDictionary> _callback;
			UIViewController _parentController;

			public ScannerCameraDelegate (UIViewController parent)
			{
				_parentController = parent;
			}

			public void setCallback (Action<NSDictionary> callback)
			{
				_callback = callback;
			}
			
			public override void FinishedPickingMedia (UIImagePickerController picker, NSDictionary info)
			{
				var cb = _callback;
				_callback = null;
				
//				picker.DismissViewController (false, null);
				//				_parentController.DismissViewController(true, null);
				cb (info);
//				_parentController.DismissViewController(true, null);
				_parentController.PerformSegue("ProductScannedSegue", _parentController);
			}
		}
	}
}
