// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using CoreGraphics;

using Foundation;
using UIKit;

using TimesSquare.iOS;

namespace OneTradeCentral.iOS
{
	public partial class RequiredDateController : UIViewController
	{
		public OrderViewController OrderController { get; set; }
		public DateTime SelectedDate { get; set; }

		public RequiredDateController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

//			var calendarViewArea = new RectangleF (0, 0, View.Bounds.Width, View.Bounds.Height - 88);
			var calendarViewArea = View.Bounds;
			NSDate chosenDate = NSDate.Now;
			if (SelectedDate != DateTime.MinValue)
				chosenDate = NSDate.FromTimeIntervalSinceReferenceDate((SelectedDate-(new DateTime(2001,1,1,0,0,0))).TotalSeconds);
			var nSCalendar = new NSCalendar (NSCalendarType.Gregorian);
			nSCalendar.TimeZone = NSTimeZone.LocalTimeZone;
			var calendarView = new TSQCalendarView (calendarViewArea) {
				Calendar = nSCalendar,
				RowCellClass = new ObjCRuntime.Class ("CalendarRowCell"),
				FirstDate = NSDate.Now,
				// average of 30 days per month, 7 months
				LastDate = NSDate.FromTimeIntervalSinceNow (60 * 60 * 24 * 30 * 7),
				BackgroundColor = UIColor.LightTextColor,
				PagingEnabled = true
			};

			if (SelectedDate != DateTime.MinValue)
				calendarView.SelectedDate = chosenDate;

			calendarView.DidSelectDate += (sender, e) => {
				SelectedDate = (DateTime) e.Date;
			};

			View.Add (calendarView);
		}

		partial void Save (Foundation.NSObject sender) {
			// Fix for #60.  Remove Required Date and Payment Terms, not needed by Wrigley's
//			OrderController.setRequiredDate (SelectedDate.ToLocalTime());
			NavigationController.PopViewController(true);
		}
	}
}
