// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using Foundation;
using UIKit;

namespace OneTradeCentral.iOS
{
	public partial class StoreSelectionController : UIViewController
	{
		public StoreSelectionController (IntPtr handle) : base (handle)
		{
		}

		public OrderViewController OrderViewController { get; set; }

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);
			if (segue.Identifier == "CustomerListSegue") {
				var customerListController = segue.DestinationViewController as StoreListController;
				if (customerListController != null)
					customerListController.OrderController = OrderViewController;
			}
		}

		partial void dismiss (Foundation.NSObject sender) {
			DismissViewController(true, null);
		}
	}
}
