// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;
using System.Collections.Generic;
using System.Linq;
using Foundation;
using UIKit;
using OneTradeCentral.DTOs;

namespace OneTradeCentral.iOS
{
	public partial class WarehouseController : UIViewController
	{
		static IList<ProviderWarehouse> warehouseList;
		public OrderViewController OrderController { get; set; }
//		WarehousePickerModel warehouseSource;

		public WarehouseController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			DALFacade dal = new DALFacade ();
			warehouseList = dal.getWarehouseListByProviderID (OrderController.ProviderID);
			WarehousePicker.Model = new WarehousePickerModel (OrderController);
			//			warehouseSource = new WarehousePickerModel ();
		}

		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);

			if (warehouseList.Count () > 0) {
				Customer c = OrderController.SelectedCustomer;
				var selectedRow = 0;
				ProviderWarehouse selectedWarehouse = warehouseList [0];
				if (c != null && c.PK > 0) {
					string stateCode = c.StateCode == null ? "" : c.StateCode;
					var warehouseQuery = warehouseList.Where (w => w.Name.Contains (stateCode));
					if (warehouseQuery != null && warehouseQuery.Count () > 0) {
						selectedWarehouse = warehouseQuery.First ();
//					WarehousePicker.Model.Selected (WarehousePicker, i, 0);
					}
				} 
				selectedRow = warehouseList.IndexOf (selectedWarehouse);
				WarehousePicker.Select (selectedRow, 0, false);
				OrderController.SelectWarehouse (selectedWarehouse);
			}
		}

		public class WarehousePickerModel : UIPickerViewModel
		{
			public OrderViewController _orderViewController;

			public WarehousePickerModel(OrderViewController orderViewController) {
				this._orderViewController = orderViewController;
			}

			public override nint GetComponentCount (UIPickerView picker)
			{
				return 1;
			}

			public override string GetTitle (UIPickerView picker, nint row, nint component)
			{
				return warehouseList[(int)row].Name;
			}

			public override nint GetRowsInComponent (UIPickerView picker, nint component)
			{
				return warehouseList.Count;
			}

			public override void Selected (UIPickerView picker, nint row, nint component)
			{
				_orderViewController.SelectWarehouse(warehouseList[(int)row]);
			}
		}
	}
}
