// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace OneTradeCentral.iOS
{
	public partial class TestCntrl : UIViewController
	{
		public TestCntrl (IntPtr handle) : base (handle)
		{
		}
	}
}
