// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using System.Collections.Generic;

using Foundation;
using UIKit;

using OneTradeCentral.DTOs;

namespace OneTradeCentral.iOS
{
	public partial class LogViewController : UIViewController
	{

		public OrderStatusController orderStatusController { get; set; }

		public LogViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			TableView.Source = new LogViewSource ();

//			// Resize OrderStatusController here
//			System.Drawing.SizeF pSize = new System.Drawing.SizeF (216, 216);
//			orderStatusController.PreferredContentSize = pSize;
//
		}

		partial void dismiss (Foundation.NSObject sender) {
			DismissViewController(true, null);
		}

		partial void mailLogs (Foundation.NSObject sender) {
		}

		public class LogViewSource : UITableViewSource {

			IList<Log> logEntries = Logger.getAllLogs ();
			private static string cellID = "LogEntryCell";
//			const int maxMessageLength = 30;

			public override nint NumberOfSections (UITableView tableView)
			{
				return 1;
			}

			public override nint RowsInSection (UITableView tableview, nint section)
			{
				return logEntries.Count;
			}

			public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
			{
				UITableViewCell cell = tableView.DequeueReusableCell (cellID);
				var message = logEntries [indexPath.Row].message;
//				if (message.Length > maxMessageLength)
//					message = message.Substring (0, maxMessageLength);
				cell.TextLabel.Text = message;
				cell.DetailTextLabel.Text = logEntries [indexPath.Row].logTimeStamp.ToString("yyyy-MMM-d hh:mm:ss tt");
				return cell;
			}
		}
	}
}
