// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;

using Foundation;
using UIKit;

namespace OneTradeCentral.iOS
{
	public partial class ProductScannerController : UIImagePickerController
	{
		public ProductScannerController (IntPtr handle) : base (handle)
		{
			setSourceType();
		}

		public ProductScannerController () : base ()
		{
			setSourceType();
		}

		private void setSourceType ()
		{
			
			if (IsSourceTypeAvailable (UIImagePickerControllerSourceType.Camera))
				SourceType = UIImagePickerControllerSourceType.Camera;
			else {
				SourceType = UIImagePickerControllerSourceType.PhotoLibrary;
			}
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
		}
	}
}
