// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using CoreGraphics;

using Foundation;
using UIKit;
using ObjCRuntime;

namespace OneTradeCentral.iOS
{
	public partial class ProductImageController : UIViewController
	{
//		private Int32 _pageIndex;

		public ProductImageController (IntPtr handle) : base (handle)
		{
		}

		public ProductImageController(Int32 pageIndex)
		{
//			this._pageIndex = pageIndex;
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			if (UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Phone)
			{
				ProductBrowserView view = new ProductBrowserView () { Frame = View.Frame };
				View.AddSubview (view);
			} else {
				ProductBrowserViewPad view = new ProductBrowserViewPad () { Frame = View.Frame };
				View.AddSubview (view);
			}
		}

		public override void LoadView ()
		{
			base.LoadView ();
		}
	}
}
