// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;

using Foundation;
using UIKit;

using OneTradeCentral.DTOs;

namespace OneTradeCentral.iOS
{
	public partial class ScannedProductController : UIViewController
	{
		public OrderViewController OrderViewController { get; set; }

		public Product Product { get; set; }
		public int Quantity { get; set; }

		DALFacade DALFacade { get; set; }

		public ScannedProductController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			if (DALFacade == null)
				DALFacade = new DALFacade ();
			NavigationItem.SetHidesBackButton (true, false);
//			ScannedProduct = DALFacade.getProduct (BarCodeType.Composite, "abcdefghij");
			if (Product != null) {
				ProductNameLabel.Text = Product.Name;
				VendorNameLabel.Text = Product.VendorName;
//				BarcodeIDLabel.Text = Product.BarcodeID;
				SKULabel.Text = Product.SKU.ToString ();
//				UnitPriceLabel.Text = Product.UnitPrice.ToString ();
				QuantityStepper.Value = Quantity;
//				setAmountValue(Quantity);
			}
		}

		public void setProductImage (UIImage image)
		{
			if (this.ProductImageView == null)
				this.ProductImageView = new UIImageView ();
			this.ProductImageView.Image = image;
		}

//		partial void stepperAction (MonoTouch.Foundation.NSObject sender)
//		{
//			var stepper = sender as UIStepper;
//			setAmountValue (stepper.Value);
//		}

//		void setAmountValue (double stepperValue)
//		{
//			QuantityField.Text = stepperValue.ToString ();
//			var amount = new Decimal (stepperValue) * Product.UnitPrice;
//			AmountLabel.Text = amount.ToString ();
//		}

		partial void addItem (Foundation.NSObject sender)
		{
			var quantity = Convert.ToInt32 (QuantityField.Text);
			if (quantity > 0) {
				OrderViewController.AddOrderLineItem (Product, Convert.ToInt32 (QuantityField.Text));
				DismissViewController (true, null);
			}
		}

		partial void dismiss (Foundation.NSObject sender)
		{
			DismissViewController (true, null);
//			_parentController.PopToRootViewController(false);
		}
	}
}
