// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OneTradeCentral.iOS.OrdersWebService {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="mobileservicesSoap", Namespace="http://4solutions.co.au/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mobileservices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IsOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailNotificationOperationCompleted;
        
        private System.Threading.SendOrPostCallback VersionControlOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReferenceDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback LastReleaseDateOperationCompleted;
        
        public mobileservices() {
            
        }
        
        public mobileservices(string url) {
            this.Url = url;
        }
        
        public event IsOnlineCompletedEventHandler IsOnlineCompleted;
        
        public event EmailNotificationCompletedEventHandler EmailNotificationCompleted;
        
        public event VersionControlCompletedEventHandler VersionControlCompleted;
        
        public event GetReferenceDataCompletedEventHandler GetReferenceDataCompleted;
        
        public event SubmitOrderCompletedEventHandler SubmitOrderCompleted;
        
        public event CreateErrorCompletedEventHandler CreateErrorCompleted;
        
        public event LastReleaseDateCompletedEventHandler LastReleaseDateCompleted;
        
        /// <remarks>
///Returns true, webservice is active.
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://4solutions.co.au/IsOnline", RequestNamespace="http://4solutions.co.au/", ResponseNamespace="http://4solutions.co.au/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public bool IsOnline() {
            object[] results = this.Invoke("IsOnline", new object[0]);
            return ((bool)(results[0]));
        }
        
        public System.IAsyncResult BeginIsOnline(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsOnline", new object[0], callback, asyncState);
        }
        
        public bool EndIsOnline(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        public void IsOnlineAsync() {
            this.IsOnlineAsync(null);
        }
        
        public void IsOnlineAsync(object userState) {
            if ((this.IsOnlineOperationCompleted == null)) {
                this.IsOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsOnlineCompleted);
            }
            this.InvokeAsync("IsOnline", new object[0], this.IsOnlineOperationCompleted, userState);
        }
        
        private void OnIsOnlineCompleted(object arg) {
            if ((this.IsOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsOnlineCompleted(this, new IsOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Test email notification.
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://4solutions.co.au/EmailNotification", RequestNamespace="http://4solutions.co.au/", ResponseNamespace="http://4solutions.co.au/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public bool EmailNotification(string Email, out string ErrorMessage) {
            object[] results = this.Invoke("EmailNotification", new object[] {
                        Email});
            ErrorMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        public System.IAsyncResult BeginEmailNotification(string Email, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmailNotification", new object[] {
                        Email}, callback, asyncState);
        }
        
        public bool EndEmailNotification(System.IAsyncResult asyncResult, out string ErrorMessage) {
            object[] results = this.EndInvoke(asyncResult);
            ErrorMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        public void EmailNotificationAsync(string Email) {
            this.EmailNotificationAsync(Email, null);
        }
        
        public void EmailNotificationAsync(string Email, object userState) {
            if ((this.EmailNotificationOperationCompleted == null)) {
                this.EmailNotificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailNotificationCompleted);
            }
            this.InvokeAsync("EmailNotification", new object[] {
                        Email}, this.EmailNotificationOperationCompleted, userState);
        }
        
        private void OnEmailNotificationCompleted(object arg) {
            if ((this.EmailNotificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailNotificationCompleted(this, new EmailNotificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Check Application Version
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://4solutions.co.au/VersionControl", RequestNamespace="http://4solutions.co.au/", ResponseNamespace="http://4solutions.co.au/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public bool VersionControl(string VersionMajor, string VersionMinor, out string ErroMessage) {
            object[] results = this.Invoke("VersionControl", new object[] {
                        VersionMajor,
                        VersionMinor});
            ErroMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        public System.IAsyncResult BeginVersionControl(string VersionMajor, string VersionMinor, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("VersionControl", new object[] {
                        VersionMajor,
                        VersionMinor}, callback, asyncState);
        }
        
        public bool EndVersionControl(System.IAsyncResult asyncResult, out string ErroMessage) {
            object[] results = this.EndInvoke(asyncResult);
            ErroMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        public void VersionControlAsync(string VersionMajor, string VersionMinor) {
            this.VersionControlAsync(VersionMajor, VersionMinor, null);
        }
        
        public void VersionControlAsync(string VersionMajor, string VersionMinor, object userState) {
            if ((this.VersionControlOperationCompleted == null)) {
                this.VersionControlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVersionControlCompleted);
            }
            this.InvokeAsync("VersionControl", new object[] {
                        VersionMajor,
                        VersionMinor}, this.VersionControlOperationCompleted, userState);
        }
        
        private void OnVersionControlCompleted(object arg) {
            if ((this.VersionControlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VersionControlCompleted(this, new VersionControlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///gets reference data for a sales Organization
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://4solutions.co.au/GetReferenceData", RequestNamespace="http://4solutions.co.au/", ResponseNamespace="http://4solutions.co.au/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public System.Data.DataSet GetReferenceData(long salesOrgNo, long repAccountNo, string mOrderLincVersion, string mIOSVersion) {
            object[] results = this.Invoke("GetReferenceData", new object[] {
                        salesOrgNo,
                        repAccountNo,
                        mOrderLincVersion,
                        mIOSVersion});
            return ((System.Data.DataSet)(results[0]));
        }
        
        public System.IAsyncResult BeginGetReferenceData(long salesOrgNo, long repAccountNo, string mOrderLincVersion, string mIOSVersion, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetReferenceData", new object[] {
                        salesOrgNo,
                        repAccountNo,
                        mOrderLincVersion,
                        mIOSVersion}, callback, asyncState);
        }
        
        public System.Data.DataSet EndGetReferenceData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        public void GetReferenceDataAsync(long salesOrgNo, long repAccountNo, string mOrderLincVersion, string mIOSVersion) {
            this.GetReferenceDataAsync(salesOrgNo, repAccountNo, mOrderLincVersion, mIOSVersion, null);
        }
        
        public void GetReferenceDataAsync(long salesOrgNo, long repAccountNo, string mOrderLincVersion, string mIOSVersion, object userState) {
            if ((this.GetReferenceDataOperationCompleted == null)) {
                this.GetReferenceDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReferenceDataCompleted);
            }
            this.InvokeAsync("GetReferenceData", new object[] {
                        salesOrgNo,
                        repAccountNo,
                        mOrderLincVersion,
                        mIOSVersion}, this.GetReferenceDataOperationCompleted, userState);
        }
        
        private void OnGetReferenceDataCompleted(object arg) {
            if ((this.GetReferenceDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReferenceDataCompleted(this, new GetReferenceDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Accepts mobile orders and the signature image array associated with it.
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://4solutions.co.au/SubmitOrder", RequestNamespace="http://4solutions.co.au/", ResponseNamespace="http://4solutions.co.au/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public long SubmitOrder(DTOOrder order, byte[] imageArray, DTOContact contact, string uName, string uPW, string deviceNo, out string ServerMessage) {
            object[] results = this.Invoke("SubmitOrder", new object[] {
                        order,
                        imageArray,
                        contact,
                        uName,
                        uPW,
                        deviceNo});
            ServerMessage = ((string)(results[1]));
            return ((long)(results[0]));
        }
        
        public System.IAsyncResult BeginSubmitOrder(DTOOrder order, byte[] imageArray, DTOContact contact, string uName, string uPW, string deviceNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SubmitOrder", new object[] {
                        order,
                        imageArray,
                        contact,
                        uName,
                        uPW,
                        deviceNo}, callback, asyncState);
        }
        
        public long EndSubmitOrder(System.IAsyncResult asyncResult, out string ServerMessage) {
            object[] results = this.EndInvoke(asyncResult);
            ServerMessage = ((string)(results[1]));
            return ((long)(results[0]));
        }
        
        public void SubmitOrderAsync(DTOOrder order, byte[] imageArray, DTOContact contact, string uName, string uPW, string deviceNo) {
            this.SubmitOrderAsync(order, imageArray, contact, uName, uPW, deviceNo, null);
        }
        
        public void SubmitOrderAsync(DTOOrder order, byte[] imageArray, DTOContact contact, string uName, string uPW, string deviceNo, object userState) {
            if ((this.SubmitOrderOperationCompleted == null)) {
                this.SubmitOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitOrderCompleted);
            }
            this.InvokeAsync("SubmitOrder", new object[] {
                        order,
                        imageArray,
                        contact,
                        uName,
                        uPW,
                        deviceNo}, this.SubmitOrderOperationCompleted, userState);
        }
        
        private void OnSubmitOrderCompleted(object arg) {
            if ((this.SubmitOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitOrderCompleted(this, new SubmitOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Creates error
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://4solutions.co.au/CreateError", RequestNamespace="http://4solutions.co.au/", ResponseNamespace="http://4solutions.co.au/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public int CreateError() {
            object[] results = this.Invoke("CreateError", new object[0]);
            return ((int)(results[0]));
        }
        
        public System.IAsyncResult BeginCreateError(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateError", new object[0], callback, asyncState);
        }
        
        public int EndCreateError(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        public void CreateErrorAsync() {
            this.CreateErrorAsync(null);
        }
        
        public void CreateErrorAsync(object userState) {
            if ((this.CreateErrorOperationCompleted == null)) {
                this.CreateErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateErrorCompleted);
            }
            this.InvokeAsync("CreateError", new object[0], this.CreateErrorOperationCompleted, userState);
        }
        
        private void OnCreateErrorCompleted(object arg) {
            if ((this.CreateErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateErrorCompleted(this, new CreateErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Check The Last Release Date of the Web Service
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://4solutions.co.au/LastReleaseDate", RequestNamespace="http://4solutions.co.au/", ResponseNamespace="http://4solutions.co.au/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public string LastReleaseDate() {
            object[] results = this.Invoke("LastReleaseDate", new object[0]);
            return ((string)(results[0]));
        }
        
        public System.IAsyncResult BeginLastReleaseDate(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LastReleaseDate", new object[0], callback, asyncState);
        }
        
        public string EndLastReleaseDate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        public void LastReleaseDateAsync() {
            this.LastReleaseDateAsync(null);
        }
        
        public void LastReleaseDateAsync(object userState) {
            if ((this.LastReleaseDateOperationCompleted == null)) {
                this.LastReleaseDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLastReleaseDateCompleted);
            }
            this.InvokeAsync("LastReleaseDate", new object[0], this.LastReleaseDateOperationCompleted, userState);
        }
        
        private void OnLastReleaseDateCompleted(object arg) {
            if ((this.LastReleaseDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LastReleaseDateCompleted(this, new LastReleaseDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://4solutions.co.au/")]
    public partial class DTOOrder {
        
        /// <remarks/>
        public long OrderID;
        
        /// <remarks/>
        public long SalesOrgID;
        
        /// <remarks/>
        public long CustomerID;
        
        /// <remarks/>
        public long SalesRepAccountID;
        
        /// <remarks/>
        public long ProviderID;
        
        /// <remarks/>
        public int ProviderWarehouseID;
        
        /// <remarks/>
        public System.DateTime OrderDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="dateTime")]
        public System.Nullable<System.DateTime> DeliveryDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="dateTime")]
        public System.Nullable<System.DateTime> InvoiceDate;
        
        /// <remarks/>
        public int SYSOrderStatusID;
        
        /// <remarks/>
        public string OrderNumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="dateTime")]
        public System.Nullable<System.DateTime> ReceivedDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="dateTime")]
        public System.Nullable<System.DateTime> ReleaseDate;
        
        /// <remarks/>
        public bool IsSent;
        
        /// <remarks/>
        public bool IsHeld;
        
        /// <remarks/>
        public System.DateTime DateCreated;
        
        /// <remarks/>
        public System.DateTime DateUpdated;
        
        /// <remarks/>
        public long CreatedByUserID;
        
        /// <remarks/>
        public long UpdatedByUserID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="dateTime")]
        public System.Nullable<System.DateTime> HoldUntilDate;
        
        /// <remarks/>
        public bool IsMobile;
        
        /// <remarks/>
        public string OrderGUID;
        
        /// <remarks/>
        public string ProviderCustomerCode;
        
        /// <remarks/>
        public DTOOrderLine[] OrderLine;
        
        /// <remarks/>
        public string SYSOrderStatusText;
        
        /// <remarks/>
        public string CustomerName;
        
        /// <remarks/>
        public string ProviderName;
        
        /// <remarks/>
        public string CreatedByName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="boolean")]
        public System.Nullable<bool> IsRegularOrder;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="dateTime")]
        public System.Nullable<System.DateTime> RequestedReleaseDate;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://4solutions.co.au/")]
    public partial class DTOOrderLine {
        
        /// <remarks/>
        public long OrderLineID;
        
        /// <remarks/>
        public long OrderID;
        
        /// <remarks/>
        public int LineNum;
        
        /// <remarks/>
        public long ProductID;
        
        /// <remarks/>
        public float OrderQty;
        
        /// <remarks/>
        public float DespatchQty;
        
        /// <remarks/>
        public string UOM;
        
        /// <remarks/>
        public float OrderPrice;
        
        /// <remarks/>
        public float DespatchPrice;
        
        /// <remarks/>
        public string ItemStatus;
        
        /// <remarks/>
        public string ErrorText;
        
        /// <remarks/>
        public float Discount;
        
        /// <remarks/>
        public string ProductCode;
        
        /// <remarks/>
        public string PrimarySKU;
        
        /// <remarks/>
        public string ProductName;
        
        /// <remarks/>
        public string GTINCode;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://4solutions.co.au/")]
    public partial class DTOContact {
        
        /// <remarks/>
        public long ContactID;
        
        /// <remarks/>
        public string Phone;
        
        /// <remarks/>
        public string Fax;
        
        /// <remarks/>
        public string Mobile;
        
        /// <remarks/>
        public string Email;
        
        /// <remarks/>
        public string LastName;
        
        /// <remarks/>
        public string FirstName;
        
        /// <remarks/>
        public long CreatedByUserID;
        
        /// <remarks/>
        public long OldID;
    }
    
    public partial class IsOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    public delegate void IsOnlineCompletedEventHandler(object sender, IsOnlineCompletedEventArgs args);
    
    public partial class EmailNotificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailNotificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        public string ErrorMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    public delegate void EmailNotificationCompletedEventHandler(object sender, EmailNotificationCompletedEventArgs args);
    
    public partial class VersionControlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VersionControlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        public string ErroMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    public delegate void VersionControlCompletedEventHandler(object sender, VersionControlCompletedEventArgs args);
    
    public partial class GetReferenceDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReferenceDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    public delegate void GetReferenceDataCompletedEventHandler(object sender, GetReferenceDataCompletedEventArgs args);
    
    public partial class SubmitOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
        
        public string ServerMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    public delegate void SubmitOrderCompletedEventHandler(object sender, SubmitOrderCompletedEventArgs args);
    
    public partial class CreateErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    public delegate void CreateErrorCompletedEventHandler(object sender, CreateErrorCompletedEventArgs args);
    
    public partial class LastReleaseDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LastReleaseDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    public delegate void LastReleaseDateCompletedEventHandler(object sender, LastReleaseDateCompletedEventArgs args);
}
