// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using Foundation;
using UIKit;

namespace OneTradeCentral.iOS
{
	public partial class ContactSelectionController : UIViewController
	{
		public OrderViewController OrderViewController { get; set; }

		public ContactSelectionController (IntPtr handle) : base (handle)
		{
		}

		partial void dismiss (Foundation.NSObject sender) {
			DismissViewController(true, null);
		}
	}
}
